In [2]:
import pickle as pkl
from torch.utils.data import DataLoader
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [3]:
with open("data/pickles/50salads_target.pkl", "rb") as f:
    salads_target = pkl.load(f)

with open("data/pickles/50salads_softmax.pkl", "rb") as f:
    salads_predict = pkl.load(f)

In [34]:
from itertools import chain
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(np.array(list(chain.from_iterable(salads_target))).reshape(-1, 1))
one_hot_salads = [encoder.transform(x.reshape(-1, 1)) for x in salads_target]

In [38]:
with open("data/pickles/50_salads_one_hot.pkl", "wb") as f:
    pkl.dump(one_hot_salads, f)

In [10]:
with open("data/pickles/50_salads_one_hot.pkl", "rb") as f:
    one_hot_salads = pkl.load(f)

In [11]:
one_hot_salads

[array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 arr

In [12]:
from dataset.dataset import SaladsDataset

dataset = SaladsDataset(one_hot_salads)

In [14]:
next(iter(dataset)).shape

torch.Size([5687, 18])