In [5]:
import pickle as pkl
from torch.utils.data import DataLoader
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [6]:
with open("data/pickles/50salads_target.pkl", "rb") as f:
    salads_target = pkl.load(f)

with open("data/pickles/50salads_softmax.pkl", "rb") as f:
    salads_predict = pkl.load(f)

In [7]:
from sklearn.preprocessing import OneHotEncoder

def one_hot_encode(l):
    encoder = OneHotEncoder(sparse_output=False)
    return encoder.fit_transform(np.array(l).reshape(-1, 1))

In [8]:
one_hot_salads = [one_hot_encode(x) for x in salads_target]

In [9]:
with open("data/pickles/50_salads_one_hot.pkl", "wb") as f:
    pkl.dump(one_hot_salads, f)

In [10]:
with open("data/pickles/50_salads_one_hot.pkl", "rb") as f:
    one_hot_salads = pkl.load(f)

In [11]:
one_hot_salads

[array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 arr

In [12]:
from dataset.dataset import SaladsDataset

dataset = SaladsDataset(one_hot_salads)

In [14]:
next(iter(dataset)).shape

torch.Size([5687, 18])