In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import json
from utils.Config import Config

with open("config.json", "r") as f:
    cfg_json = json.load(f)
    cfg = Config(**cfg_json)

In [3]:
import pickle as pkl
from dataset.dataset import SaladsDataset

with open("../data/pickles/breakfast_unified.pkl", "rb") as f:
    dataset = pkl.load(f)

salads_dataset = SaladsDataset(dataset['target'], dataset['stochastic'])

In [4]:
from sklearn.model_selection import train_test_split

train_dataset, test_dataset = train_test_split(salads_dataset, train_size=0.7, shuffle=True, random_state=42)

In [5]:
from utils.pm_utils import discover_dk_process, remove_duplicates_dataset

dk_process_model, dk_init_marking, dk_final_marking = discover_dk_process(train_dataset, cfg, preprocess=remove_duplicates_dataset)

In [6]:
from src.utils.graph_utils import get_feature_collections, add_features_to_graph
import pm4py

model_nx = pm4py.convert_petri_net_to_networkx(dk_process_model, dk_init_marking, dk_final_marking)

feature_collections = get_feature_collections(model_nx, cfg)
add_features_to_graph(model_nx, feature_collections)

In [7]:
types = set()

for n, attrs in model_nx.nodes(data=True):
    types.add(attrs["attr"]["type"])

In [13]:
from utils.graph_utils import prepare_process_model_for_heterognn

pm_nx_data = prepare_process_model_for_heterognn(dk_process_model, dk_init_marking, dk_final_marking, cfg)

In [27]:
pm_nx_data.edge_attrs()

['edge_index']

In [16]:
pm_nx_data["place"].x

tensor([[  0],
        [  1],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9],
        [ 10],
        [ 11],
        [ 12],
        [ 13],
        [ 14],
        [ 15],
        [ 16],
        [ 17],
        [ 18],
        [ 19],
        [ 20],
        [ 21],
        [ 22],
        [ 23],
        [ 24],
        [ 25],
        [ 26],
        [ 27],
        [ 28],
        [ 29],
        [ 30],
        [ 31],
        [ 32],
        [ 33],
        [ 34],
        [ 35],
        [ 36],
        [ 37],
        [ 38],
        [ 39],
        [ 40],
        [ 41],
        [ 42],
        [ 43],
        [ 44],
        [ 45],
        [ 46],
        [ 47],
        [ 48],
        [ 49],
        [ 50],
        [ 51],
        [ 52],
        [ 53],
        [ 54],
        [ 55],
        [ 56],
        [ 57],
        [ 58],
        [ 59],
        [ 60],
        [ 61],
        [ 62],
        [ 63],
        [ 64],
        [ 65],
        [ 

In [32]:
from modules.HeteroGraphEncoder import HeteroGraphEncoder

h_enc = HeteroGraphEncoder(pm_nx_data.metadata(), {n_type: pm_nx_data[n_type].num_nodes for n_type in pm_nx_data.node_types}, 128, 128, 128, pooling="add")

In [33]:
out_h = h_enc(pm_nx_data)

In [34]:
out_h

tensor([[  2.1829, -46.2185, -20.2622, -54.3207,  -8.2687,   1.2888,   2.8761,
          -4.8327, -33.2255,  43.7968,  17.7247,  16.7886, -39.7370, -19.1966,
         -49.5252,  12.2319,  40.0262, -29.2258, -10.8208,   5.6721,   1.0921,
          46.1219, -17.8544,   8.3256, -18.2760,  12.5593,  -4.1834,  13.0356,
          13.2243, -16.9675,  -3.5562,  -2.5378,   5.2587,   5.8921, -17.1842,
          25.2788,  13.4384,  32.3539, -29.9968,  -7.7086, -34.6169,   6.9660,
          -0.5349, -12.1462,  16.2914,  10.6670,   1.5175, -25.2505,   9.5026,
          -3.4716,  -8.8902,   3.9249, -20.4631,  -4.2877,  21.3035,  -0.3272,
           6.7890, -60.2256,  13.4344, -12.9831,   7.3959,  21.7972,   1.9126,
          30.2831,  -7.3169, -12.2827,   7.9782,  11.7366,   5.8101,  -7.6537,
           7.7793,  55.5322, -24.9075,   5.3280,  19.1227,  15.5453,   3.5942,
           3.7571,  54.1198, -26.2210,   6.2768, -27.2158, -15.8532,  14.7190,
          11.6066,  28.7097,  10.9921,  -9.0125,   1

In [18]:
from src.utils.graph_utils import prepare_process_model_for_gnn

pm_nx_data = prepare_process_model_for_gnn(dk_process_model, dk_init_marking, dk_final_marking, cfg)

C:\Users\Maxim\anaconda3\Lib\site-packages\torch_geometric\utils\convert.py:278: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  data_dict[key] = torch.as_tensor(value)


In [19]:
pm_nx_data.x

tensor([[247],
        [246],
        [245],
        [244],
        [243],
        [242],
        [241],
        [240],
        [239],
        [238],
        [237],
        [236],
        [235],
        [234],
        [233],
        [232],
        [231],
        [230],
        [229],
        [228],
        [227],
        [226],
        [225],
        [224],
        [223],
        [222],
        [221],
        [220],
        [219],
        [218],
        [217],
        [216],
        [215],
        [214],
        [213],
        [212],
        [211],
        [210],
        [209],
        [208],
        [207],
        [206],
        [205],
        [204],
        [203],
        [202],
        [201],
        [200],
        [199],
        [198],
        [197],
        [196],
        [195],
        [194],
        [193],
        [192],
        [191],
        [190],
        [189],
        [188],
        [187],
        [186],
        [185],
        [184],
        [183],
        [182],
        [1

In [7]:
from utils.graph_utils import get_process_model_petri_net_transition_matrix
import torch

rg_nx, rg_transition_matrix = get_process_model_petri_net_transition_matrix(dk_process_model,
                                                                                        dk_init_marking,
                                                                                        dk_final_marking)
rg_transition_matrix = torch.tensor(rg_transition_matrix, device=cfg.device).unsqueeze(0).float()

In [14]:
from modules.GraphEncoder import GraphEncoder

g_enc = GraphEncoder(pm_nx_data.num_nodes, 128, 128, 128, pooling=None, conv_type="gin").to(cfg.device).float()
g_enc_add = GraphEncoder(pm_nx_data.num_nodes, 128, 128, 128).to(cfg.device).float()

In [15]:
pm_nx_data = pm_nx_data.to(cfg.device)

In [16]:
out_g = g_enc(pm_nx_data)

In [17]:
out_g_add = g_enc_add(pm_nx_data)

In [18]:
out_g.shape

torch.Size([248, 128])

In [17]:
from modules.GPSGraphEncoder import GPSGraphEncoder

gps_enc = GPSGraphEncoder(pm_nx_data.num_nodes).to(cfg.device)

In [18]:
gps_enc(pm_nx_data)

tensor([[ 1.1455e-01, -2.3044e-01,  7.7353e-02,  1.5637e-01, -3.8996e-02,
          2.3642e-01,  1.8649e-01, -2.4842e-01,  2.7754e-01, -2.4390e-01,
          2.5757e-02, -2.3198e-01, -1.1258e-01,  1.3795e-01, -3.1045e-02,
          2.1474e-02,  3.7689e-03, -2.3639e-01,  2.1930e-01, -3.2777e-02,
          1.4851e-01,  3.0859e-01,  5.6461e-02, -1.6508e-01,  2.8071e-01,
         -3.2719e-01,  4.0509e-03, -2.7674e-01,  3.3085e-01, -7.0256e-02,
          3.0164e-01, -1.2166e-01,  7.3045e-02, -3.4861e-02, -6.5103e-02,
         -1.3883e-01,  5.1055e-01, -4.5663e-01, -1.1720e-01,  1.9582e-02,
         -1.0648e-01,  1.6981e-01, -5.0277e-02,  2.4448e-02,  8.5197e-02,
         -1.2556e-01, -1.7314e-01, -7.2981e-02,  3.5583e-02,  4.9703e-02,
          1.7977e-01, -1.4681e-01,  1.2579e-01,  2.7148e-02, -7.6920e-02,
         -1.6628e-01,  3.1316e-01, -1.0636e-01, -2.2127e-01,  3.1380e-01,
          2.9516e-02, -1.3896e-01,  7.5745e-02, -2.2781e-01,  3.4043e-01,
         -4.2164e-02, -3.1808e-01, -1.

In [12]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
        train_dataset,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=8
    )

dummy_x, dummy_y = (w.permute(0, 2, 1).to(cfg.device).float() for w in next(iter(train_loader)))

In [13]:
from ddpm.ddpm_multinomial import Diffusion

diffuser = Diffusion(noise_steps=cfg.num_timesteps, device=cfg.device)

In [19]:
from denoisers.ConditionalUnetGraphDenoiser import ConditionalUnetGraphDenoiser

graph_denoiser_atn = ConditionalUnetGraphDenoiser(in_ch=cfg.num_classes, out_ch=cfg.num_classes, max_input_dim=salads_dataset.sequence_length, graph_data=pm_nx_data, num_nodes=pm_nx_data.num_nodes, embedding_dim=128, hidden_dim=128, pooling=None).to(cfg.device)

In [20]:
graph_denoiser = ConditionalUnetGraphDenoiser(in_ch=cfg.num_classes, out_ch=cfg.num_classes, max_input_dim=salads_dataset.sequence_length, graph_data=pm_nx_data, num_nodes=pm_nx_data.num_nodes, embedding_dim=128, hidden_dim=128, pooling='mean').to(cfg.device)

In [21]:
from denoisers.ConditionalUnetMatrixDenoiser import ConditionalUnetMatrixDenoiser

matrix_denoiser = ConditionalUnetMatrixDenoiser(in_ch=cfg.num_classes, out_ch=cfg.num_classes,
                                                 max_input_dim=salads_dataset.sequence_length,
                                                 transition_dim=rg_transition_matrix.shape[-1],
                                                 gamma=cfg.gamma,
                                                 matrix_out_channels=rg_transition_matrix.shape[0],
                                                 device=cfg.device).to(cfg.device).float()

In [22]:
sum(p.numel() for p in matrix_denoiser.parameters() if p.requires_grad)

46505010

In [23]:
sum(p.numel() for p in graph_denoiser.parameters() if p.requires_grad)

18676465

In [24]:
sum(p.numel() for p in graph_denoiser_atn.parameters() if p.requires_grad)

20758769

In [27]:
t = diffuser.sample_timesteps(dummy_x.shape[0]).to(cfg.device)

In [28]:
graph_denoiser(dummy_x, t, None, None)[0].shape

RuntimeError: shape '[3, 64, -1]' is invalid for input of size 4672