In [37]:
import pickle as pkl
import torch
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from scipy.stats import entropy

In [6]:
with open(r"../data/pickles/50_salads_unified.pkl", "rb") as f:
    data = pkl.load(f)

det, sto = data['target'], data['stochastic']

In [13]:
def average_entropy(seq):
    return np.mean([entropy(x) for x in seq])

In [17]:
np.mean([average_entropy(x) for x in sto])

0.24932393

In [12]:
def add_dirichlet_noise(p, alpha=0.1, noise_level=0.1):
    """
    p: original probability vector (e.g., one-hot)
    alpha: concentration parameter for the Dirichlet distribution.
           Lower alpha makes the Dirichlet sample more "peaky".
    noise_level: mixing coefficient for the noise.
    """
    # Generate a Dirichlet noise vector.
    noise = np.random.dirichlet(np.ones_like(p) * alpha)
    # Mix the original distribution with the noise.
    perturbed = (1 - noise_level) * p + noise_level * noise
    # Ensure it sums to 1.
    perturbed /= perturbed.sum()
    return perturbed

array([2.52486041e-11, 2.47556978e-02, 5.83787198e-10, 1.98117341e-08,
       6.34690629e-02, 3.56077731e-03, 3.33457075e-11, 8.74130410e-10,
       1.71214102e-06, 8.85385304e-11, 4.15604228e-03, 1.75597866e-12,
       2.95994907e-05, 3.16040178e-08, 1.19971000e-05, 1.11400631e-05,
       1.91448426e-03, 9.02006094e-01, 8.33392166e-05])

In [51]:
my_sto = [add_dirichlet_noise(x, alpha=1000, noise_level=0.4) for x in det[0]]

In [52]:
my_sto

[array([0.02162687, 0.02107   , 0.02086982, 0.02158947, 0.01970446,
        0.02181436, 0.02167271, 0.02128858, 0.02222414, 0.02173012,
        0.02169094, 0.02077353, 0.01978084, 0.02042815, 0.01969778,
        0.02105347, 0.02125139, 0.62146502, 0.02026835]),
 array([0.02026889, 0.02150998, 0.02172234, 0.02196916, 0.02106195,
        0.02129049, 0.02089736, 0.02099725, 0.02170688, 0.02194173,
        0.02082946, 0.02069011, 0.02106033, 0.02067975, 0.0216171 ,
        0.01997062, 0.01967984, 0.62118956, 0.02091719]),
 array([0.0211298 , 0.02113322, 0.02042662, 0.02053867, 0.02103586,
        0.02127204, 0.02097024, 0.02059161, 0.02159614, 0.0207632 ,
        0.02196653, 0.0215643 , 0.02097764, 0.0199952 , 0.02092361,
        0.02122604, 0.02179479, 0.62114838, 0.02094612]),
 array([0.02172043, 0.02119368, 0.02105773, 0.02101512, 0.02017658,
        0.02158081, 0.02035537, 0.02169843, 0.0215176 , 0.02236569,
        0.02056482, 0.02015263, 0.01994183, 0.02123968, 0.02095145,
        0.

In [53]:
px.bar(x=range(my_sto[0].shape[0]), y=my_sto[0])

In [24]:
average_entropy(my_sto)

0.32035843165305744